// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartGest.API.Data;

#nullable disable

namespace SmartGest.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610221759_Fix_Seed_ContasContabeis")]
    partial class Fix_Seed_ContasContabeis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartGest.API.Models.CategoriaContabil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AplicaImpostoSelo")
                        .HasColumnType("boolean");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("ContaCredito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContaDebito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrupoBalanco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrupoDre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrupoFluxoCaixa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CategoriaContabeis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "71",
                            ContaDebito = "45",
                            GrupoBalanco = "",
                            GrupoDre = "Proveitos e Ganhos",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Venda de Mercadoria",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 2,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "72",
                            ContaDebito = "45",
                            GrupoBalanco = "",
                            GrupoDre = "Proveitos e Ganhos",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Prestação de Serviço",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 3,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "31",
                            ContaDebito = "45",
                            GrupoBalanco = "",
                            GrupoDre = "",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Recebimento de Cliente",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 4,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "73",
                            ContaDebito = "45",
                            GrupoBalanco = "",
                            GrupoDre = "Proveitos e Ganhos",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Outros Rendimentos",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 5,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "51",
                            ContaDebito = "45",
                            GrupoBalanco = "",
                            GrupoDre = "",
                            GrupoFluxoCaixa = "Financiamento",
                            Nome = "Capital Inicial",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 6,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "33",
                            ContaDebito = "45",
                            GrupoBalanco = "",
                            GrupoDre = "",
                            GrupoFluxoCaixa = "Financiamento",
                            Nome = "Empréstimo Bancário",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 7,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "78",
                            ContaDebito = "45",
                            GrupoBalanco = "",
                            GrupoDre = "Proveitos e Ganhos",
                            GrupoFluxoCaixa = "Financiamento",
                            Nome = "Juros Recebidos",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 8,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "79",
                            ContaDebito = "45",
                            GrupoBalanco = "",
                            GrupoDre = "Proveitos e Ganhos",
                            GrupoFluxoCaixa = "Investimento",
                            Nome = "Venda de Ativo",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 9,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "72",
                            ContaDebito = "45",
                            GrupoBalanco = "",
                            GrupoDre = "Proveitos e Ganhos",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Comissão Recebida",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 10,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "73",
                            ContaDebito = "45",
                            GrupoBalanco = "",
                            GrupoDre = "Proveitos e Ganhos",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Outras Entradas",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 11,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "45",
                            ContaDebito = "61",
                            GrupoBalanco = "",
                            GrupoDre = "Custos e Perdas",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Compra de Mercadoria",
                            Tipo = "Saída"
                        },
                        new
                        {
                            Id = 12,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "45",
                            ContaDebito = "32",
                            GrupoBalanco = "",
                            GrupoDre = "",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Pagamento a Fornecedor",
                            Tipo = "Saída"
                        },
                        new
                        {
                            Id = 13,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "45",
                            ContaDebito = "63",
                            GrupoBalanco = "",
                            GrupoDre = "Custos e Perdas",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Salários",
                            Tipo = "Saída"
                        },
                        new
                        {
                            Id = 14,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "36",
                            ContaDebito = "63",
                            GrupoBalanco = "",
                            GrupoDre = "Custos e Perdas",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "INSS",
                            Tipo = "Saída"
                        },
                        new
                        {
                            Id = 15,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "34",
                            ContaDebito = "65",
                            GrupoBalanco = "",
                            GrupoDre = "Custos e Perdas",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "IRT",
                            Tipo = "Saída"
                        },
                        new
                        {
                            Id = 16,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "34",
                            ContaDebito = "65",
                            GrupoBalanco = "",
                            GrupoDre = "Custos e Perdas",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "IVA",
                            Tipo = "Saída"
                        },
                        new
                        {
                            Id = 17,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "34",
                            ContaDebito = "65",
                            GrupoBalanco = "",
                            GrupoDre = "Custos e Perdas",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Impostos e Taxas",
                            Tipo = "Saída"
                        },
                        new
                        {
                            Id = 18,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "45",
                            ContaDebito = "62",
                            GrupoBalanco = "",
                            GrupoDre = "Custos e Perdas",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Despesa Administrativa",
                            Tipo = "Saída"
                        },
                        new
                        {
                            Id = 19,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "45",
                            ContaDebito = "62",
                            GrupoBalanco = "",
                            GrupoDre = "Custos e Perdas",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Energia / Água / Internet",
                            Tipo = "Saída"
                        },
                        new
                        {
                            Id = 20,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "45",
                            ContaDebito = "62",
                            GrupoBalanco = "",
                            GrupoDre = "Custos e Perdas",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Aluguer",
                            Tipo = "Saída"
                        },
                        new
                        {
                            Id = 21,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "45",
                            ContaDebito = "62",
                            GrupoBalanco = "",
                            GrupoDre = "Custos e Perdas",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Combustível / Transportes",
                            Tipo = "Saída"
                        },
                        new
                        {
                            Id = 22,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "45",
                            ContaDebito = "11",
                            GrupoBalanco = "",
                            GrupoDre = "",
                            GrupoFluxoCaixa = "Investimento",
                            Nome = "Compra de Equipamento",
                            Tipo = "Saída"
                        },
                        new
                        {
                            Id = 23,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "45",
                            ContaDebito = "68",
                            GrupoBalanco = "",
                            GrupoDre = "Custos e Perdas",
                            GrupoFluxoCaixa = "Financiamento",
                            Nome = "Juros Bancários",
                            Tipo = "Saída"
                        },
                        new
                        {
                            Id = 24,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "45",
                            ContaDebito = "33",
                            GrupoBalanco = "",
                            GrupoDre = "",
                            GrupoFluxoCaixa = "Financiamento",
                            Nome = "Amortização de Empréstimo",
                            Tipo = "Saída"
                        },
                        new
                        {
                            Id = 25,
                            AplicaImpostoSelo = false,
                            Ativo = true,
                            ContaCredito = "45",
                            ContaDebito = "66",
                            GrupoBalanco = "",
                            GrupoDre = "Custos e Perdas",
                            GrupoFluxoCaixa = "Operacional",
                            Nome = "Outras Despesas",
                            Tipo = "Saída"
                        });
                });

            modelBuilder.Entity("SmartGest.API.Models.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnimacoesAtivadas")
                        .HasColumnType("boolean");

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DataFormatoIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("DoisFatoresAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailNotificacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdiomaIndex")
                        .HasColumnType("integer");

                    b.Property<decimal>("LimiarSaldoBaixo")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MoedaIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("MostrarSaldosOcultos")
                        .HasColumnType("boolean");

                    b.Property<bool>("MostrarSparklines")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifApp")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifBackup")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifErrosSistema")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifLancamentos")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifRelatorios")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifSaldoBaixo")
                        .HasColumnType("boolean");

                    b.Property<bool>("RegistarAuditoria")
                        .HasColumnType("boolean");

                    b.Property<bool>("RetryAtivado")
                        .HasColumnType("boolean");

                    b.Property<int>("SessaoTimeoutMins")
                        .HasColumnType("integer");

                    b.Property<int>("TemaIndex")
                        .HasColumnType("integer");

                    b.Property<int>("TimeoutIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("TlsAtivado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Configuracoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimacoesAtivadas = true,
                            ApiBaseUrl = "",
                            ApiKey = "",
                            DataFormatoIndex = 0,
                            DoisFatoresAtivo = false,
                            EmailNotificacoes = "",
                            IdiomaIndex = 0,
                            LimiarSaldoBaixo = 500000m,
                            MoedaIndex = 0,
                            MostrarSaldosOcultos = false,
                            MostrarSparklines = true,
                            NotifApp = true,
                            NotifBackup = true,
                            NotifEmail = true,
                            NotifErrosSistema = true,
                            NotifLancamentos = true,
                            NotifRelatorios = false,
                            NotifSaldoBaixo = true,
                            RegistarAuditoria = true,
                            RetryAtivado = true,
                            SessaoTimeoutMins = 30,
                            TemaIndex = 0,
                            TimeoutIndex = 1,
                            TlsAtivado = true
                        });
                });

            modelBuilder.Entity("SmartGest.API.Models.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ContaContabilId")
                        .HasColumnType("integer");

                    b.Property<string>("CorAccent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NIB")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SaldoOntem")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContaContabilId");

                    b.HasIndex("NIB")
                        .IsUnique();

                    b.ToTable("ContasBancarias");
                });

            modelBuilder.Entity("SmartGest.API.Models.ContaContabil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsDevedora")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("ContasContabeis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Codigo = "11",
                            Grupo = "Ativo",
                            IsDevedora = true,
                            Nome = "Activos Fixos Tangíveis"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Codigo = "12",
                            Grupo = "Ativo",
                            IsDevedora = true,
                            Nome = "Activos Intangíveis"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Codigo = "13",
                            Grupo = "Ativo",
                            IsDevedora = true,
                            Nome = "Investimentos Financeiros"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Codigo = "18",
                            Grupo = "Ativo",
                            IsDevedora = false,
                            Nome = "Amortizações Acumuladas"
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Codigo = "22",
                            Grupo = "Ativo",
                            IsDevedora = true,
                            Nome = "Mercadorias"
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Codigo = "26",
                            Grupo = "Ativo",
                            IsDevedora = true,
                            Nome = "Matérias-Primas e Subsidiárias"
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            Codigo = "31",
                            Grupo = "Ativo",
                            IsDevedora = true,
                            Nome = "Clientes"
                        },
                        new
                        {
                            Id = 8,
                            Activa = true,
                            Codigo = "32",
                            Grupo = "Passivo",
                            IsDevedora = false,
                            Nome = "Fornecedores"
                        },
                        new
                        {
                            Id = 9,
                            Activa = true,
                            Codigo = "33",
                            Grupo = "Passivo",
                            IsDevedora = false,
                            Nome = "Empréstimos Obtidos"
                        },
                        new
                        {
                            Id = 10,
                            Activa = true,
                            Codigo = "34",
                            Grupo = "Passivo",
                            IsDevedora = false,
                            Nome = "Estado e Outros Entes Públicos"
                        },
                        new
                        {
                            Id = 11,
                            Activa = true,
                            Codigo = "36",
                            Grupo = "Passivo",
                            IsDevedora = false,
                            Nome = "Pessoal"
                        },
                        new
                        {
                            Id = 12,
                            Activa = true,
                            Codigo = "43",
                            Grupo = "Ativo",
                            IsDevedora = true,
                            Nome = "Caixa"
                        },
                        new
                        {
                            Id = 13,
                            Activa = true,
                            Codigo = "45",
                            Grupo = "Ativo",
                            IsDevedora = true,
                            Nome = "Depósitos Bancários"
                        },
                        new
                        {
                            Id = 14,
                            Activa = true,
                            Codigo = "51",
                            Grupo = "Capital",
                            IsDevedora = false,
                            Nome = "Capital Social"
                        },
                        new
                        {
                            Id = 15,
                            Activa = true,
                            Codigo = "55",
                            Grupo = "Capital",
                            IsDevedora = false,
                            Nome = "Reservas Legais"
                        },
                        new
                        {
                            Id = 16,
                            Activa = true,
                            Codigo = "59",
                            Grupo = "Capital",
                            IsDevedora = false,
                            Nome = "Resultados Transitados"
                        },
                        new
                        {
                            Id = 17,
                            Activa = true,
                            Codigo = "61",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Custo das Mercadorias Vendidas"
                        },
                        new
                        {
                            Id = 18,
                            Activa = true,
                            Codigo = "62",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Fornecimentos e Serviços de Terceiros"
                        },
                        new
                        {
                            Id = 19,
                            Activa = true,
                            Codigo = "63",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Gastos com Pessoal"
                        },
                        new
                        {
                            Id = 20,
                            Activa = true,
                            Codigo = "64",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Amortizações e Depreciações do Exercício"
                        },
                        new
                        {
                            Id = 21,
                            Activa = true,
                            Codigo = "65",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Impostos e Taxas"
                        },
                        new
                        {
                            Id = 22,
                            Activa = true,
                            Codigo = "66",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Outros Custos e Perdas Operacionais"
                        },
                        new
                        {
                            Id = 23,
                            Activa = true,
                            Codigo = "68",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Custos e Perdas Financeiras"
                        },
                        new
                        {
                            Id = 24,
                            Activa = true,
                            Codigo = "69",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Custos e Perdas Extraordinárias"
                        },
                        new
                        {
                            Id = 25,
                            Activa = true,
                            Codigo = "71",
                            Grupo = "Receita",
                            IsDevedora = false,
                            Nome = "Vendas de Mercadorias e Produtos Acabados"
                        },
                        new
                        {
                            Id = 26,
                            Activa = true,
                            Codigo = "72",
                            Grupo = "Receita",
                            IsDevedora = false,
                            Nome = "Prestações de Serviços"
                        },
                        new
                        {
                            Id = 27,
                            Activa = true,
                            Codigo = "73",
                            Grupo = "Receita",
                            IsDevedora = false,
                            Nome = "Outros Proveitos e Ganhos Operacionais"
                        },
                        new
                        {
                            Id = 28,
                            Activa = true,
                            Codigo = "78",
                            Grupo = "Receita",
                            IsDevedora = false,
                            Nome = "Proveitos e Ganhos Financeiros"
                        },
                        new
                        {
                            Id = 29,
                            Activa = true,
                            Codigo = "79",
                            Grupo = "Receita",
                            IsDevedora = false,
                            Nome = "Proveitos e Ganhos Extraordinários"
                        },
                        new
                        {
                            Id = 30,
                            Activa = true,
                            Codigo = "88",
                            Grupo = "Capital",
                            IsDevedora = false,
                            Nome = "Resultado Líquido do Exercício"
                        });
                });

            modelBuilder.Entity("SmartGest.API.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Capital")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capital = 10000000m,
                            Cidade = "Luanda",
                            Email = "geral@smartgest.ao",
                            Morada = "Rua da Missão, 42 · Luanda Sul",
                            NIF = "5417000001",
                            Nome = "SmartGest, Lda.",
                            Pais = "Angola",
                            Telefone = "+244 923 000 000",
                            Website = "www.smartgest.ao"
                        });
                });

            modelBuilder.Entity("SmartGest.API.Models.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AanuladoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AanuladoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("Anulado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Beneficiario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CaminhoDocumento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CategoriaContabilId")
                        .HasColumnType("integer");

                    b.Property<string>("CentroCusto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ContaBancariaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ImpostoSelo")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MotivoAnulacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReferenciaInterna")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Anulado")
                        .HasDatabaseName("IX_Lancamento_Anulado");

                    b.HasIndex("CategoriaContabilId");

                    b.HasIndex("ContaBancariaId");

                    b.HasIndex("Data")
                        .HasDatabaseName("IX_Lancamento_Data");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("SmartGest.API.Models.LancamentoDetalhe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaContabilId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Credito")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Debito")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("LancamentoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LancamentoId");

                    b.HasIndex("ContaContabilId", "Debito", "Credito")
                        .HasDatabaseName("IX_LancamentoDetalhe_ContaContabilId_Debito_Credito");

                    b.ToTable("LancamentoDetalhes");
                });

            modelBuilder.Entity("SmartGest.API.Models.MovimentoBancario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaBancariaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaId");

                    b.ToTable("MovimentosBancarios");
                });

            modelBuilder.Entity("SmartGest.API.Models.SessaoActiva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dispositivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAtual")
                        .HasColumnType("boolean");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UltimaActividade")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("SmartGest.API.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CorAvatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Iniciais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Operador");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("Utilizadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CorAvatar = "#1A2E5A",
                            CriadoEm = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "weber@smartgest.ao",
                            Iniciais = "JW",
                            Nome = "Jeth Weber",
                            PasswordHash = "$2b$11$a.TPqwNMTgPENS9Up.20f.CzgkVrSgpLt0KGfl3vWEWKeq/hEK7Rq",
                            Perfil = "Administrador",
                            Telefone = "900000000"
                        });
                });

            modelBuilder.Entity("SmartGest.API.Models.Webhook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Webhooks");
                });

            modelBuilder.Entity("SmartGest.API.Models.ContaBancaria", b =>
                {
                    b.HasOne("SmartGest.API.Models.ContaContabil", "ContaContabil")
                        .WithMany()
                        .HasForeignKey("ContaContabilId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContaContabil");
                });

            modelBuilder.Entity("SmartGest.API.Models.Lancamento", b =>
                {
                    b.HasOne("SmartGest.API.Models.CategoriaContabil", "CategoriaContabil")
                        .WithMany()
                        .HasForeignKey("CategoriaContabilId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartGest.API.Models.ContaBancaria", "ContaBancaria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CategoriaContabil");

                    b.Navigation("ContaBancaria");
                });

            modelBuilder.Entity("SmartGest.API.Models.LancamentoDetalhe", b =>
                {
                    b.HasOne("SmartGest.API.Models.ContaContabil", "ContaContabil")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaContabilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartGest.API.Models.Lancamento", "Lancamento")
                        .WithMany("Detalhes")
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaContabil");

                    b.Navigation("Lancamento");
                });

            modelBuilder.Entity("SmartGest.API.Models.MovimentoBancario", b =>
                {
                    b.HasOne("SmartGest.API.Models.ContaBancaria", "ContaBancaria")
                        .WithMany("Movimentos")
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaBancaria");
                });

            modelBuilder.Entity("SmartGest.API.Models.SessaoActiva", b =>
                {
                    b.HasOne("SmartGest.API.Models.Utilizador", "Utilizador")
                        .WithMany("Sessoes")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("SmartGest.API.Models.ContaBancaria", b =>
                {
                    b.Navigation("Lancamentos");

                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("SmartGest.API.Models.ContaContabil", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("SmartGest.API.Models.Lancamento", b =>
                {
                    b.Navigation("Detalhes");
                });

            modelBuilder.Entity("SmartGest.API.Models.Utilizador", b =>
                {
                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
