// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartGest.API.Data;

#nullable disable

namespace SmartGest.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SmartGest.API.Models.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnimacoesAtivadas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DataFormatoIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoisFatoresAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailNotificacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdiomaIndex")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LimiarSaldoBaixo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MoedaIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MostrarSaldosOcultos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MostrarSparklines")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifApp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifBackup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifErrosSistema")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifLancamentos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifRelatorios")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifSaldoBaixo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RegistarAuditoria")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RetryAtivado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessaoTimeoutMins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemaIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeoutIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TlsAtivado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configuracoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimacoesAtivadas = true,
                            ApiBaseUrl = "",
                            ApiKey = "",
                            DataFormatoIndex = 0,
                            DoisFatoresAtivo = false,
                            EmailNotificacoes = "",
                            IdiomaIndex = 0,
                            LimiarSaldoBaixo = 500000m,
                            MoedaIndex = 0,
                            MostrarSaldosOcultos = false,
                            MostrarSparklines = true,
                            NotifApp = true,
                            NotifBackup = true,
                            NotifEmail = true,
                            NotifErrosSistema = true,
                            NotifLancamentos = true,
                            NotifRelatorios = false,
                            NotifSaldoBaixo = true,
                            RegistarAuditoria = true,
                            RetryAtivado = true,
                            SessaoTimeoutMins = 30,
                            TemaIndex = 0,
                            TimeoutIndex = 1,
                            TlsAtivado = true
                        });
                });

            modelBuilder.Entity("SmartGest.API.Models.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorAccent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("NIB")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoOntem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NIB")
                        .IsUnique();

                    b.ToTable("ContasBancarias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Agencia = "Luanda — Maianga",
                            Banco = "Banco BIC",
                            CorAccent = "#1A2E5A",
                            Moeda = "AOA",
                            NIB = "AO06.0055.0000.1234.5678.9012.3",
                            SaldoAtual = 4820000m,
                            SaldoOntem = 4600000m,
                            Tipo = "Conta à Ordem",
                            Titular = "SmartGest, Lda."
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Agencia = "Luanda — Ingombota",
                            Banco = "Banco BAI",
                            CorAccent = "#0D47A1",
                            Moeda = "AOA",
                            NIB = "AO06.0040.0000.9876.5432.1098.7",
                            SaldoAtual = 3150000m,
                            SaldoOntem = 3200000m,
                            Tipo = "Conta à Ordem",
                            Titular = "SmartGest, Lda."
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Agencia = "Luanda — Samba",
                            Banco = "Banco BPC",
                            CorAccent = "#1B5E20",
                            Moeda = "AOA",
                            NIB = "AO06.0038.0000.1111.2222.3333.4",
                            SaldoAtual = 2980000m,
                            SaldoOntem = 2980000m,
                            Tipo = "Depósito a Prazo",
                            Titular = "SmartGest, Lda."
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Agencia = "Luanda — Talatona",
                            Banco = "Banco ATL",
                            CorAccent = "#E65100",
                            Moeda = "USD",
                            NIB = "AO06.0006.0000.4444.5555.6666.7",
                            SaldoAtual = 1530000m,
                            SaldoOntem = 1490000m,
                            Tipo = "Conta à Ordem",
                            Titular = "SmartGest, Lda."
                        });
                });

            modelBuilder.Entity("SmartGest.API.Models.ContaContabil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDevedora")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("ContasContabeis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Codigo = "11",
                            Grupo = "Ativo",
                            IsDevedora = true,
                            Nome = "Caixa e Equivalentes de Caixa"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Codigo = "12",
                            Grupo = "Ativo",
                            IsDevedora = true,
                            Nome = "Clientes e Outras Contas a Receber"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Codigo = "13",
                            Grupo = "Ativo",
                            IsDevedora = true,
                            Nome = "Inventários e Activos Biológicos"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Codigo = "14",
                            Grupo = "Ativo",
                            IsDevedora = true,
                            Nome = "Activos Fixos Tangíveis"
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Codigo = "15",
                            Grupo = "Ativo",
                            IsDevedora = true,
                            Nome = "Activos Intangíveis"
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Codigo = "21",
                            Grupo = "Passivo",
                            IsDevedora = false,
                            Nome = "Fornecedores e Contas a Pagar"
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            Codigo = "22",
                            Grupo = "Passivo",
                            IsDevedora = false,
                            Nome = "Empréstimos Bancários"
                        },
                        new
                        {
                            Id = 8,
                            Activa = true,
                            Codigo = "23",
                            Grupo = "Passivo",
                            IsDevedora = false,
                            Nome = "Encargos sobre Remunerações"
                        },
                        new
                        {
                            Id = 9,
                            Activa = true,
                            Codigo = "24",
                            Grupo = "Passivo",
                            IsDevedora = false,
                            Nome = "Imposto a Pagar (IRT / IVA)"
                        },
                        new
                        {
                            Id = 10,
                            Activa = true,
                            Codigo = "31",
                            Grupo = "Capital",
                            IsDevedora = false,
                            Nome = "Capital Social"
                        },
                        new
                        {
                            Id = 11,
                            Activa = true,
                            Codigo = "32",
                            Grupo = "Capital",
                            IsDevedora = false,
                            Nome = "Reservas Legais"
                        },
                        new
                        {
                            Id = 12,
                            Activa = true,
                            Codigo = "33",
                            Grupo = "Capital",
                            IsDevedora = false,
                            Nome = "Resultados Transitados"
                        },
                        new
                        {
                            Id = 13,
                            Activa = true,
                            Codigo = "71",
                            Grupo = "Receita",
                            IsDevedora = false,
                            Nome = "Vendas de Mercadorias"
                        },
                        new
                        {
                            Id = 14,
                            Activa = true,
                            Codigo = "72",
                            Grupo = "Receita",
                            IsDevedora = false,
                            Nome = "Prestações de Serviços"
                        },
                        new
                        {
                            Id = 15,
                            Activa = true,
                            Codigo = "73",
                            Grupo = "Receita",
                            IsDevedora = false,
                            Nome = "Outros Rendimentos Operacionais"
                        },
                        new
                        {
                            Id = 16,
                            Activa = true,
                            Codigo = "78",
                            Grupo = "Receita",
                            IsDevedora = false,
                            Nome = "Proveitos e Ganhos Financeiros"
                        },
                        new
                        {
                            Id = 17,
                            Activa = true,
                            Codigo = "79",
                            Grupo = "Receita",
                            IsDevedora = false,
                            Nome = "Proveitos Extraordinários"
                        },
                        new
                        {
                            Id = 18,
                            Activa = true,
                            Codigo = "61",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Custo das Mercadorias Vendidas"
                        },
                        new
                        {
                            Id = 19,
                            Activa = true,
                            Codigo = "62",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Fornecimentos e Serviços Externos"
                        },
                        new
                        {
                            Id = 20,
                            Activa = true,
                            Codigo = "63",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Gastos com Pessoal"
                        },
                        new
                        {
                            Id = 21,
                            Activa = true,
                            Codigo = "64",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Amortizações e Depreciações"
                        },
                        new
                        {
                            Id = 22,
                            Activa = true,
                            Codigo = "65",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Impostos e Taxas"
                        },
                        new
                        {
                            Id = 23,
                            Activa = true,
                            Codigo = "66",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Outros Custos Operacionais"
                        },
                        new
                        {
                            Id = 24,
                            Activa = true,
                            Codigo = "68",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Custos e Perdas Financeiras"
                        },
                        new
                        {
                            Id = 25,
                            Activa = true,
                            Codigo = "69",
                            Grupo = "Despesa",
                            IsDevedora = true,
                            Nome = "Custos Extraordinários"
                        });
                });

            modelBuilder.Entity("SmartGest.API.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Capital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capital = 10000000m,
                            Cidade = "Luanda",
                            Email = "geral@smartgest.ao",
                            Morada = "Rua da Missão, 42 · Luanda Sul",
                            NIF = "5417000001",
                            Nome = "SmartGest, Lda.",
                            Pais = "Angola",
                            Telefone = "+244 923 000 000",
                            Website = "www.smartgest.ao"
                        });
                });

            modelBuilder.Entity("SmartGest.API.Models.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beneficiario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoDocumento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CentroCusto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContaBancariaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenciaInterna")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaId");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("SmartGest.API.Models.LancamentoDetalhe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContaContabilId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Credito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Debito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LancamentoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContaContabilId");

                    b.HasIndex("LancamentoId");

                    b.ToTable("LancamentoDetalhes");
                });

            modelBuilder.Entity("SmartGest.API.Models.MovimentoBancario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContaBancariaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaId");

                    b.ToTable("MovimentosBancarios");
                });

            modelBuilder.Entity("SmartGest.API.Models.SessaoActiva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dispositivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAtual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaActividade")
                        .HasColumnType("TEXT");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("SmartGest.API.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorAvatar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Iniciais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Operador");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("Utilizadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CorAvatar = "#1A2E5A",
                            CriadoEm = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "augusto@smartgest.ao",
                            Iniciais = "AB",
                            Nome = "Augusto Barbosa",
                            PasswordHash = "$2a$11$W6k9CR/erDeuqTYNChrLiutX.MZ2kdzXydirBWQ82ihKjeJlSIw32",
                            Perfil = "Administrador",
                            Telefone = "900000000"
                        });
                });

            modelBuilder.Entity("SmartGest.API.Models.Webhook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Webhooks");
                });

            modelBuilder.Entity("SmartGest.API.Models.Lancamento", b =>
                {
                    b.HasOne("SmartGest.API.Models.ContaBancaria", "ContaBancaria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContaBancaria");
                });

            modelBuilder.Entity("SmartGest.API.Models.LancamentoDetalhe", b =>
                {
                    b.HasOne("SmartGest.API.Models.ContaContabil", "ContaContabil")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaContabilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartGest.API.Models.Lancamento", "Lancamento")
                        .WithMany("Detalhes")
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaContabil");

                    b.Navigation("Lancamento");
                });

            modelBuilder.Entity("SmartGest.API.Models.MovimentoBancario", b =>
                {
                    b.HasOne("SmartGest.API.Models.ContaBancaria", "ContaBancaria")
                        .WithMany("Movimentos")
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaBancaria");
                });

            modelBuilder.Entity("SmartGest.API.Models.SessaoActiva", b =>
                {
                    b.HasOne("SmartGest.API.Models.Utilizador", "Utilizador")
                        .WithMany("Sessoes")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("SmartGest.API.Models.ContaBancaria", b =>
                {
                    b.Navigation("Lancamentos");

                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("SmartGest.API.Models.ContaContabil", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("SmartGest.API.Models.Lancamento", b =>
                {
                    b.Navigation("Detalhes");
                });

            modelBuilder.Entity("SmartGest.API.Models.Utilizador", b =>
                {
                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
